const KycStatusTypes = Object.freeze({
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  UPDATED: 'UPDATED',
  SUBMITTED: 'SUBMITTED',
  COMPLETED_CLEAR: 'COMPLETED.CLEAR',
  COMPLETED_REJECTED: 'COMPLETED.REJECTED',
});

export default KycStatusTypes;
